### ISSUE TITLE
To-do for initial commit of new filter-and-download

### ISSUE THREAD

**Issue by meiqimichelle** [DOI-ONRR/doi-extractives-data#305]
- [x] get the tabs working (location with dataset, over time with dataset)
- [x] in the table: remove y-axis scroll bar
- [x] in the table: when 'more' happens, the entire div should expand right to give more space
- [x] in the table: remove white lines between rows
- [x] in the table: chevron sort indicators need to flip with sort
- [x] data is not correct in 'inner' rollovers. should just be whatever is displaying on the bar.
- [x] back/reset on chart
- [x] legend needs to be there for when bars split (oil & gas, for example)
- [x] x-axis labels after click should match names and capitalizations on revenue types buttons
- [x] chart needs an x-axis label: "Commodities" as per mockup
- [x] need to be able to link to a tab on the data page (for example, the map footnote will link to the data-by-location section of the filter and download page)
- [x] Buttons need to work with dive in charts 
- [x] 'on-dive' something needs to show that you're 'in' 'oil&gas'
  ![screenshot 2014-12-02 12 29 31](https://cloud.githubusercontent.com/assets/4827522/5269346/08fec4a0-7a1f-11e4-9ca0-f09f7cc55b4b.png)
