### ISSUE TITLE
ONRR feedback for beta launch

### ISSUE THREAD

**Issue by meiqimichelle** [DOI-ONRR/doi-extractives-data#322]
- [x] First story, first sentence: change “extracted from its lands.” To “extracted from its federal lands, both onshore and offshore.”
- [x] In the “How do natural resources become Federal revenue” narrative, first paragraph, change “grant” to “issue”
- [x] In the “How do natural resources become Federal revenue” narrative, second paragraph, change last sentence to “There are other revenues involved, such as rents, bonuses, fees, and penalties, but by far most of the money comes from royalties.”
- [x] There are issues with the scale on the map page. For example, when viewing oil, Arkansas only has $7.87 in revenues, but the scale shows a minimum of $17,820. Maybe we don’t need numbers on the scale?
- [x] On the pie chart, can we add the text “Choose a Commodity” above the commodity selections? This would be consistent with the map page, and would alleviate some confusion about the “Other” selection. There’s continued angst about the word other not being qualified with “Commodities” or “Revenues” throughout the site.
- [x] Add the year, the year type, and the word “Federal” to the data page. (2013 calendar year ONRR data. Federal.)
- [x] ~~The Other issue on the bar chart -- 'other' is not always the same 'other' on the x-axis. Label which is which.~~ _moved to #328_
- [x] ~~colors for break-downs are wrong on renewables — need a texture indicator, not a color so that the legend will make sense.~~ _moved to #343_
- [x] on the revenues chart, add instructions so that people know you can click on a commodity name to 'dive'
- [x] ~~adjust tooltip question marks. Text inside is too small, and 'Can we change the tooltip indicator from a “?” to an “i”? People think the question mark is distracting and makes it look like the site has problems.'~~ _moved to #344_
